// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static java.lang.String aCT_FinalCaption(IContext context, myfirstmodule.proxies.FinalPieChartData _finalPieChartData)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("FinalPieChartData", _finalPieChartData == null ? null : _finalPieChartData.getMendixObject());
			return (java.lang.String)Core.execute(context, "MyFirstModule.ACT_FinalCaption", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String aCT_FinalValue(IContext context, myfirstmodule.proxies.FinalPieChartData _finalPieChartData)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("FinalPieChartData", _finalPieChartData == null ? null : _finalPieChartData.getMendixObject());
			return (java.lang.String)Core.execute(context, "MyFirstModule.ACT_FinalValue", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static myfirstmodule.proxies.FinalPieChartData aCT_GenerateReport(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.ACT_GenerateReport", params);
			return result == null ? null : myfirstmodule.proxies.FinalPieChartData.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_OnAppLoad(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MyFirstModule.ACT_OnAppLoad", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}